# github action to deploy munsonpickles api to azure

name: Deploy Munson Pickles API

on:
  workflow_dispatch:

env:
  # AZURE_WEBAPP_NAME: "app-munson-api-eastus-dev-001"
  ArtifactName: "TEST"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
        
      - name: Install dependencies
        run: dotnet restore ./MunsonPickles.Api/MunsonPickles.Api.csproj

      - name: Build
        run: dotnet build ./MunsonPickles.Api/MunsonPickles.Api.csproj --configuration Release --no-restore

      # publish
      - name: Publish
        run: dotnet publish ./MunsonPickles.Api/MunsonPickles.Api.csproj --configuration Release --output ./publish
        
      - name: Create zip artifact
        run: |
          cd ./publish
          zip -r ../MunsonPickles.Api.zip .
          cd ..
  
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MunsonPickles.Api
          path: MunsonPickles.Api.zip

  deployOnDev:
    runs-on: windows-latest
    needs: build
    # if: github.base_ref == 'develop' || startsWith(github.ref, 'refs/heads/feature/*')
    steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v4.0.0
      with:
        name: MunsonPickles.Api
        path: MunsonPickles.Api

    - name: Deploy using MSDeploy
      run: |
            $msdeploy = "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe"
            & $msdeploy `
            -verb:sync `
            "-source:package=MunsonPickles.Api/MunsonPickles.Api.zip" `
            "-dest:auto,computerName=https://${{ secrets.IIS_HOST }}:8172/msdeploy.axd?site=MunsonPickles.Api,userName=${{ secrets.IIS_USER }},password=${{ secrets.IIS_PASS }},authType=Basic" `
            -allowUntrusted


    # - name: Install Azure CLI
    #   run: |
    #     curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash 
        
      # deploy to azure
      # - name: Deploy to Azure Web App
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: ${{ env.AZURE_WEBAPP_NAME }}
      #     publish-profile: ${{ secrets.API_PUBLISH_SECRET }}
      #     package: ./publish
